[Settings]
ID = "6e6bb1a5-ae8a-4eb5-955a-0e9c3f8e57d4"

[context.production]
  base = "./"
  publish = "./"
  commands = ""

[context.branch-deploy]
  base = "./"
  publish = "dist/"
  command = "yarn run build"